# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8586923d552af4ada21612b9ad28a986235b2f3a5409fbfe7b9c085f45bdc5b73b7d924ab329d415e6035a8678528e9f0289d886ed7fc26586055c3c9c77101

test:
  secret_key_base: 035e6c4cc1c1106d1a84cfc840af419300bbcca88c3da7231dc8cf63f0719a4cfe9cee192751050bd7998fcfa124d462daae243a762037cbb56489f9bd0e9f10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
